In [1]:
path = [1,2,3,4,5,6,7,8,9,10]

path[::-1]

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [236]:
import numpy as np

graph = np.array(  [[0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
                    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
                    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
                    [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
                    [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]])




In [250]:
def get_boundary_edges(graph):
    # Zero the inner region
    graph[1:-1, 1:-1] = 0

    # Find positions of boundary edges
    edge_positions = np.argwhere(graph == 1)

    best_edges = set()

    # Process each boundary individually:
    for boundary, axis, idx in [('top', 0, 0), ('bottom', 0, graph.shape[0]-1),
                                ('left', 1, 0), ('right', 1, graph.shape[1]-1)]:
        edges_on_side = edge_positions[edge_positions[:, axis] == idx]

        if len(edges_on_side) == 0:
            continue

        # Sort edges based on the other coordinate
        other_axis = 1 - axis
        sorted_edges = edges_on_side[np.argsort(edges_on_side[:, other_axis])]

        # Add first and last edge if there are multiple edges, else just one
        best_edges.add(tuple(sorted_edges[0]))
        if len(sorted_edges) > 1:
            best_edges.add(tuple(sorted_edges[-1]))

    return list(best_edges)

get_boundary_edges(graph)

[(0, 3), (1, 14), (14, 10), (14, 0), (0, 14)]

In [259]:
graph[1 : - 1, 1 : - 1] = 0

edges = np.where(graph == 1)
new_edges = []
for edge in zip(*edges):
    new_edges.append(edge)
# print(new_edges)
new_edges = np.asarray(new_edges)

best_edges = []
# top row
best_indx = np.where(new_edges[:,0] == 0)[0]
best_edges.extend(new_edges[[best_indx[0], best_indx[-1]]])
# bottom row
best_indx = np.where(new_edges[:,0] == 14)[0]
best_edges.extend(new_edges[[best_indx[0], best_indx[-1]]])
# left column
best_indx = np.where(new_edges[:,1] == 0)[0]
if len(best_indx) > 1:
    best_edges.extend(new_edges[[best_indx[0], best_indx[-1]]])

# # right column
best_indx = np.where(new_edges[:,1] == 14)[0]
if len(best_indx) > 1:
    best_edges.extend(new_edges[[best_indx[0], best_indx[-1]]])

best_edges = [tuple(x) for x in best_edges ]
best_edges = list(set(best_edges))

print(best_edges[:4])

[(0, 3), (1, 14), (14, 10), (14, 0)]


In [257]:
list(set(best_edges))

[(0, 3), (1, 14), (14, 10), (14, 0), (0, 14)]

array([2, 3])

In [144]:
for i in range(new_edges.shape[1]):
    uniqs = np.unique(new_edges[:,0])
    starts = []
    ends = []
    list_of_indices = []
    for un in uniqs:
        locations = np.argwhere(new_edges[:,0] == un)
        # print("locations", locations)
        list_of_indices.append(locations[0][0].tolist())
        list_of_indices.append(locations[-1][0].tolist())
    new_edges = new_edges[list_of_indices]

# print("list_of_indices", list_of_indices)

print("new_edges", new_edges)

new_edges [[ 0  3]
 [ 0 14]
 [ 1 14]
 [ 1 14]
 [14  2]
 [14 10]]


[0]
[2]


array([[0],
       [1],
       [2]])

list_of_indices [array([0, 0, 0, 1, 0]), array([1, 1, 2, 1, 0]), array([0, 0, 0, 1, 1]), array([1, 1, 2, 1, 1]), array([0, 0, 0, 0, 1]), array([0, 1, 0, 0, 1]), array([0, 0, 0, 0, 0]), array([1, 1, 2, 0, 1])]


array([[[[[14, 10],
          [ 0,  3]],

         [[ 0, 14],
          [ 0,  3]],

         [[ 0,  3],
          [ 0,  3]]],


        [[[14, 10],
          [ 0,  3]],

         [[ 0, 14],
          [ 0,  3]],

         [[ 0,  3],
          [ 0,  3]]]],



       [[[[ 0,  3],
          [ 0,  3]],

         [[ 0,  3],
          [ 0,  3]],

         [[ 0, 14],
          [ 0,  3]]],


        [[[ 0,  3],
          [ 0,  3]],

         [[ 0,  3],
          [ 0,  3]],

         [[ 0, 14],
          [ 0,  3]]]]])

In [90]:
uniqs = np.unique(edges[1])
starts = []
ends = []
for un in uniqs:
    
    locations = np.argwhere(edges[1] == un)
    if len(locations) > 2:
        starts.append(locations[0])
        ends.append(locations[-1])


print("start", starts)
print("end", ends)

start []
end []
